"""add more fields to user

Revision ID: acc063010021
Revises: ee3b52682450
Create Date: 2022-05-10 09:14:33.852493

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'acc063010021'
down_revision = 'ee3b52682450'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.String(), server_default='male', nullable=False))
    op.add_column('users', sa.Column('age', sa.String(), server_default='age', nullable=False))
    op.drop_column('users', 'interests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('interests', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.drop_column('users', 'age')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###
