"""add images field12

Revision ID: cb143ccf7c59
Revises: 0d5b3278fcb7
Create Date: 2022-05-09 09:47:51.194304

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cb143ccf7c59'
down_revision = '0d5b3278fcb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('username', sa.String(), nullable=False,))
    op.drop_column('users', 'image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_url', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
